import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import "swiper/css";


export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en"
      data-theme="light">
      <body className=' font-Montserrat'>{children}</body>
    </html>
  )
}
